# Generated by Django 4.2.23 on 2025-08-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
